name: Telegram Notify
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *${{ github.actor }}* pushed:
            Msg: `${{ github.event.commits[0].message }}`
            
            Repository: *${{ github.repository }}*
            
            See changes: [$(echo ${{github.}} | cut -c-8)](https://github.com/${{ github.repository }}/commit/${{github.sha}})